### ISSUE TITLE
App Icons are not shown

### ISSUE THREAD

**Issue by vassilisw** [David-Hickey/windows-quick-list-2#1]
Hi,
I'm on Mint 19.3 Tricia 64-bit.
The app icons does not show up until the user hovers on any of the items.
I really hope this is not an intended behaviour since it is **less informative** and **destructive** on hover and finally there is nothing to gain from it, since it is going to enlarge **anyway**.
See [here](https://imgur.com/RcLEaIO.png) and [here](https://imgur.com/0HVND8P.png)

If somehow this is by intention, please could you tell how to disable it?

Thank you

**Comment by David-Hickey** [comment]
Latest release should've fixed it (at least on Mint 20.2) - sorry that took so long...
